//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lattes_core.WSCurriculo
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.servico.repositorio.cnpq.br/", ConfigurationName="lattes_core.WSCurriculo.WSCurriculo")]
    public interface WSCurriculo
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<byte[]> getCurriculoCompactadoAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<byte[]> getCurriculoCompactadoPorUsuarioAsync(string id, string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getDataAtualizacaoCVAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getDataAtualizacaoCVPorUsuarioAsync(string id, string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getIdentificadorCNPqAsync(string cpf, string nomeCompleto, string dataNascimento);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getIdentificadorCNPqPorUsuarioAsync(string cpf, string nomeCompleto, string dataNascimento, string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getOcorrenciaCVAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> getOcorrenciaCVPorUsuarioAsync(string id, string login);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface WSCurriculoChannel : lattes_core.WSCurriculo.WSCurriculo, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class WSCurriculoClient : System.ServiceModel.ClientBase<lattes_core.WSCurriculo.WSCurriculo>, lattes_core.WSCurriculo.WSCurriculo
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WSCurriculoClient() : 
                base(WSCurriculoClient.GetDefaultBinding(), WSCurriculoClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WSCurriculoPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSCurriculoClient(EndpointConfiguration endpointConfiguration) : 
                base(WSCurriculoClient.GetBindingForEndpoint(endpointConfiguration), WSCurriculoClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSCurriculoClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WSCurriculoClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSCurriculoClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WSCurriculoClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WSCurriculoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<byte[]> getCurriculoCompactadoAsync(string id)
        {
            return base.Channel.getCurriculoCompactadoAsync(id);
        }
        
        public System.Threading.Tasks.Task<byte[]> getCurriculoCompactadoPorUsuarioAsync(string id, string login)
        {
            return base.Channel.getCurriculoCompactadoPorUsuarioAsync(id, login);
        }
        
        public System.Threading.Tasks.Task<string> getDataAtualizacaoCVAsync(string id)
        {
            return base.Channel.getDataAtualizacaoCVAsync(id);
        }
        
        public System.Threading.Tasks.Task<string> getDataAtualizacaoCVPorUsuarioAsync(string id, string login)
        {
            return base.Channel.getDataAtualizacaoCVPorUsuarioAsync(id, login);
        }
        
        public System.Threading.Tasks.Task<string> getIdentificadorCNPqAsync(string cpf, string nomeCompleto, string dataNascimento)
        {
            return base.Channel.getIdentificadorCNPqAsync(cpf, nomeCompleto, dataNascimento);
        }
        
        public System.Threading.Tasks.Task<string> getIdentificadorCNPqPorUsuarioAsync(string cpf, string nomeCompleto, string dataNascimento, string login)
        {
            return base.Channel.getIdentificadorCNPqPorUsuarioAsync(cpf, nomeCompleto, dataNascimento, login);
        }
        
        public System.Threading.Tasks.Task<string> getOcorrenciaCVAsync(string id)
        {
            return base.Channel.getOcorrenciaCVAsync(id);
        }
        
        public System.Threading.Tasks.Task<string> getOcorrenciaCVPorUsuarioAsync(string id, string login)
        {
            return base.Channel.getOcorrenciaCVPorUsuarioAsync(id, login);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSCurriculoPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WSCurriculoPort))
            {
                return new System.ServiceModel.EndpointAddress("http://servicosweb.cnpq.br/srvcurriculo/WSCurriculo");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WSCurriculoClient.GetBindingForEndpoint(EndpointConfiguration.WSCurriculoPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WSCurriculoClient.GetEndpointAddress(EndpointConfiguration.WSCurriculoPort);
        }
        
        public enum EndpointConfiguration
        {
            
            WSCurriculoPort,
        }
    }
}
